services: 
  postgres:
    image: postgres:16
    container_name: full_stack_demo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fullstack_demo
      POSTGRES_USER: archer
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: